# This is a default pyi file for quick log functions. This file is for highlighting, 
# auto-completion and typing functions in IDEs. This default version is suitable for default list 
# of log levels. Running the module will override current contents in this file with a 
# dynamically generated version based on the actual log levels list.

def debug(msg: str, silent: bool = False) -> None: ...
def info(msg: str, silent: bool = False) -> None: ...
def warning(msg: str, silent: bool = False) -> None: ...
def error(msg: str, silent: bool = False) -> None: ...
def critical(msg: str, silent: bool = False) -> None: ...
